# Generated by Django 4.1 on 2022-08-24 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apostas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consurso", models.CharField(max_length=8)),
                ("num_selected", models.TextField(blank=True, null=True)),
                ("data", models.DateField(default=datetime.date.today)),
            ],
            options={
                "verbose_name": "Aposta",
            },
        ),
    ]
