# Generated by Django 4.1 on 2022-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loterias", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apostas",
            name="consurso",
        ),
        migrations.AddField(
            model_name="apostas",
            name="concurso",
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
